// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package entity

import (
	"time"
)

// User is an object representing the database table.
type User struct {
	ID        uint      `boil:"id" json:"id" toml:"id" yaml:"id"`
	FullName  string    `boil:"full_name" json:"full_name" toml:"full_name" yaml:"full_name"`
	CreatedAt time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *userR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var (
	userPrimaryKeyColumns = []string{"id", "full_name"}
)

type userR struct{}
type userL struct{}
